FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE=spring-boot-sample-web-static-2.1.3.RELEASE.war
COPY ${JAR_FILE} app.war
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.war"]
