FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE=spring-boot-sample-web-ui-2.1.3.RELEASE.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar","--server.servlet.context-path=/ui"]


